### ISSUE TITLE
[FEATURE] Provides configuration instructions for pulsar subscriptions

### ISSUE THREAD

**Issue by yebai1105** [streamnative/pulsar-spark#103]
At present, there is no subscriptionName-related configuration method in the pulsar-spark document, and there are relatively few other subscription-related parameter configuration instructions. I hope to provide detailed subscription configuration instructions.

**Comment by syhily** [comment]
I'm afraid that we can't set the subscription name. Because we use the Pulsar's Reader API which didn't provide such ability.

**Comment by syhily** [comment]
We have provided subscription configuration in two ways.

* `PulsarOptions.SubscriptionPrefix`: Defines the subscription prefix which is used by Pulsar's Reader API.
* `PulsarOptions.PredefinedSubscription`: We will persist the consuming status in this given subscription.
