### ISSUE TITLE
[BUG] Failed to get the subscription indicator information related to Spark's consumption of Pulsar

### ISSUE THREAD

**Issue by yebai1105** [streamnative/pulsar-spark#104]
**Describe the bug**
The subscription consumption information obtained through the command `bin/pulsar-admin topics partitioned-stats persistent://qlm-ns/qlm-test/qlm-test1 --per-partition` is all 0, which cannot truly display the consumption situation

**To Reproduce**

Consumption configuration information:

```
    val df = spark.readStream
      .format("pulsar")
      .option("service.url", serviceUrl)
      .option("admin.url", adminUrl)
      .option("topic", "persistent://qlm-ns/qlm-test/qlm-test1")
      .option("pulsar.client.authPluginClassName","org.apache.pulsar.client.impl.auth.AuthenticationToken")
      .option("pulsar.client.authParams",token)
      .load()
```

After starting to consume Pulsar, execute the command `bin/pulsar-admin topics partitioned-stats persistent://qlm-ns/qlm-test/qlm-test1 --per-partition`

Display all subscription consumption rate and throughput are 0
As shown below：

![008vxvgGgy1h8vglwsk5aj313v0sxtc6](https://user-images.githubusercontent.com/1761698/208316256-2a5d01da-a889-427c-9f34-a3d101527720.jpg)

**Comment by syhily** [comment]
Can you tell me which Spark version and pulsar-spark version you are using?
