### ISSUE TITLE
[BUG] A persistent random subscription is created each time consumption is started

### ISSUE THREAD

**Issue by yebai1105** [streamnative/pulsar-spark#105]
**Describe the bug**
A persistent random subscription name is created every time consumption is started. It is neither in the form of a reader prefixed with a subscription name nor in the form of a persistent subscription name with a fixed name, which will cause the cluster to generate a large number of subscriptions.

**To Reproduce**
Consumption configuration information:
val df = spark.readStream
.format("pulsar")
.option("service.url", serviceUrl)
.option("admin.url", adminUrl)
.option("topic", "persistent://qlm-ns/qlm-test/qlm-test1")
.option("pulsar.client.authPluginClassName","org.apache.pulsar.client.impl.auth.AuthenticationToken")
.option("pulsar.client.authParams",token)
.load()

"persistent://qlm-ns/qlm-test/qlm-test1" has 5 partitions, execute the command: "bin/pulsar-admin topics subscriptions persistent://qlm-ns/qlm-test/qlm-test1 "View：
https://tva1.sinaimg.cn/large/008vxvgGgy1h8vgzhirlxj30ve0u0alx.jpg

Every time the spark task is started, 5 persistent random subscription names will be created

**Expected behavior**
Hope to provide a reader consumption method with a subscription name prefix or a persistent consumption method with a fixed subscription name

**Comment by syhily** [comment]
This isn't a bug. It't the internal design of Pulsar's Reader API.
