### ISSUE TITLE
[BUG] Spark StreamNative Driver should not require Admin URL

### ISSUE THREAD

**Issue by vikram-narayan** [streamnative/pulsar-spark#113]
**Describe the bug**
Pulsar admins do not allow consumers/producers to access the admin URL. Consumers/producers using certificates for authentication/authorization. Teams using Spark driver cannot take advantage of Streamnative Spark Driver due to a lack of access to the admin URL.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JTBS** [comment]
I noticed this too. For internal workloads we can live with it. But clients like to send data to exposed Pulsar cluster, current version expects Admin URL to be provided.

Reason this is required from my understanding is:
-  to validate schema on target topic. 
- Create one if not present. 
- Throw error if schema on topic is not matching with incoming schema provided
- Not sure if there are other reasons a client library expects Admin URL

**Suggestion:**
Can it be at least OPTIONAL - if Admin URL is not provided, above client side checks are not done.
Its up to the broker to accept/reject message based on topic schema compatibility

**How does it work on reviewing/fixing issues with library code once approved as issue?**
- Is there a team monitoring open issues and prioritizing?
- OR is there expectation that people who post issues to contribute and patch the issue?

**Comment by JTBS** [comment]
@nlu90  Thank you for getting back

**Comment by david-streamlio** [comment]
Do you have any updates on this? For context, Verizon would like to have this by the end of April to avoid renewing a $200k contract with Confluent. So the sooner they have a timeline from us, the better off they are in the contract process. They are unable to terminate it if/until we can commit to having this.

**Comment by nlu90** [comment]
@diyankov I'm checking with the platform team.

**Comment by nlu90** [comment]
@diyankov To avoid the issue, spark job developer need to pass additional configuration to set the pulsar client behavior:

```
spark
  .readStream
  .format("pulsar")
  .option("service.url", "pulsar+ssl://localhost:6651")
  .option("pulsar.client.blockIfQueueFull","true")
```

Notice the last line in the above code section
