### ISSUE TITLE
[BUG] Error: Writing to a topic which have incompatible schema - even with same Schema Type Pulsar.STRING

### ISSUE THREAD

**Issue by JTBS** [streamnative/pulsar-spark#114]
**Describe the bug**
Error: Writing to a topic which have incompatible schema - even with same Schema Type Pulsar.STRING
Versions used: 
Pulsar 2.11.x
Pulsar-spark: pulsar-spark-connector_2.12-3.2.0.1
PySpark: 3.2.3

**To Reproduce**
1. Create DataFrame that has payload as string in "value" colum. Schema of DataFrame is below:
    root
    -- value: string
2. Try to Save DataFrame using pulsar-spark (Sample code below)
     inputData.write \
                    .mode("append") \
                    .format("pulsar") \
                    .option("service.url", "pulsar://xxxxx:6650") \
                    .option("admin.url", "http://xxxxx:8080") \
                    .option("topic", "New_NonExistingTopic_To_Test") \
                    .save() 
3. Run the Spark Job and Data Successfully published first time to Apache Pulsar Topic
4. Query schema of newly created TOPIC: You should see something like this below:
{
  "version": 0,
  "schemaInfo": {
    "name": "New_Topic_Name",
    "schema": "",
    "type": "STRING",
    "timestamp": 1677267306037,
    "properties": {}
  }
}
5. Now Try to send data again by re-running Spark job - no changes
6. ERROR: Writing to a topic which have incompatible schema

**Expected behavior**
Publish new data to topic with no errors

**Screenshots**
Stacktrace below:
Caused by: java.lang.RuntimeException: Writing to a topic which have incompatible schema
        at org.apache.spark.sql.pulsar.SchemaUtils$.uploadPulsarSchema(SchemaUtils.scala:123)
        at org.apache.spark.sql.pulsar.PulsarRowWriter.singleProducer$lzycompute(PulsarWriteTask.scala:140)
        at org.apache.spark.sql.pulsar.PulsarRowWriter.singleProducer(PulsarWriteTask.scala:138)
        at org.apache.spark.sql.pulsar.PulsarRowWriter.getProducer(PulsarWriteTask.scala:146)
        at org.apache.spark.sql.pulsar.PulsarRowWriter.sendRow(PulsarWriteTask.scala:188)
        at org.apache.spark.sql.pulsar.PulsarWriteTask.execute(PulsarWriteTask.scala:42)
        at org.apache.spark.sql.pulsar.PulsarSinks$.$anonfun$write$2(PulsarSinks.scala:154)

**Additional context**
**Workaround:**
      1. Publish to NEW topic always works
OR 2. Delete existing Schema on Topic (even if its matching Pulsar.STRING type) and Publish - it works

NOTE: Tried creating Pulsar.STRING type schema on topic upfront - but still I get above error

Looking into pulsar-spark source: few tips
- Looks like pulsar-spark source is failing to match "Pulsar.STRING" schema type derived from DataFrame (as value is of string type) and existing Schema (SchemaUtils.scala - Line 119: existingSchema.equals(schemaInfo) - its not clear why?
- Suspecting that schema equals - somehow comparing timestamp or version of newly code generated schema with existing
-  Then code tries "compatibleSchema" schema call - which is only coded to match "NONE->BYTES, BYTES->NONE"

**Comment by nlu90** [comment]
@JTBS Thanks for reporting the bug.
The issue should be solved by this linked PR.

**Comment by JTBS** [comment]
Thank you @nlu90 - really appreciate your help and time on this.
