### ISSUE TITLE
[FEATURE] Support Spark 3.3+

### ISSUE THREAD

**Issue by ikstewa** [streamnative/pulsar-spark#132]
**Is your feature request related to a problem? Please describe.**
When attempting to upgrade to spark 3.3 puslar-spark fails with a method not found exception.

**Describe the solution you'd like**
Support for Spark 3.3+

**Describe alternatives you've considered**
Downgrade to Spark 3.2

**Additional context**
```
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Cast$.apply$default$4()Z
       at org.apache.spark.sql.pulsar.PulsarRowWriter.createProjections(PulsarWriteTask.scala:103)
       at org.apache.spark.sql.pulsar.PulsarRowWriter.<init>(PulsarWriteTask.scala:124)
       at org.apache.spark.sql.pulsar.PulsarWriteTask.<init>(PulsarWriteTask.scala:32)
```

**Comment by tisonkun** [comment]
Hi @ikstewa! Thanks for reporting your use case.

May I ask what exact version of Spark you're using? When building with `-Dspark.version=3.3.0` I get a different error:

```
[ERROR] /Users/chenzili/Brittani/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala:164: value timestampFormat is not a member of org.apache.spark.sql.catalyst.json.JSONOptions
[ERROR] /Users/chenzili/Brittani/pulsar-spark/src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala:187: value timestampFormat is not a member of org.apache.spark.sql.catalyst.json.JSONOptions
```

For the version bump proposal itself, may or may not we officially bump the version, but fixing compile issue in a compatible way should be always viable IMO.

cc @nlu90 It seems pulsar-spark always associated with a fixed spark version? Or we promise a version range instead?

FYI - [tispark](https://github.com/pingcap/tispark) use profiles to provide releases for different spark (minor) versions.

**Comment by ikstewa** [comment]
My original report was a failure we received when attempting to use the existing 3.2 release with a Databricks runtime which uses Spark 3.3.

If I attempt to rebuild this library against Spark 3.3 I receive the same error you provided.

After fixing the compile errors your mentioned we were able to get this library compiled and functional on a Databricks runtime using Spark 3.4. Happy to put up a PR for the minor updates.

We were mainly hoping for a 3.3+ version of this library available as an official release in Maven.

**Comment by nlu90** [comment]
#133
