### ISSUE TITLE
[FEATURE] Bump the scala version to 2.13

### ISSUE THREAD

**Issue by yash2** [streamnative/pulsar-spark#166]
**Describe the solution you'd like**
Please bump the scala version to 2.13. With scala 2.13 and spark 3.4 compatibility will help us in testing/using spark serverless on GCP.

Example: List of GCP Dataproc Serverless Runtime versions users want to test,
2.1 (Spark 3.4, Java 17, Scala 2.13)
2.0 (Spark 3.3, Java 17, Scala 2.13)

**Additional context**
Current version supports spark 3.4 and scala v.2.12.17

**Comment by nlu90** [comment]
We will make one final release for scala 2.12 this or next week. And then, the repo will be migrated to scala 2.13

**Comment by nlu90** [comment]
#171
