### ISSUE TITLE
When set the checkpoint option about 'checkpointLocation'，missing commons-io in the shade jar

### ISSUE THREAD

**Issue by daileizhi** [streamnative/pulsar-spark#24]
VERSION:  pulsar-spark-connector_2.11-2.4.1

StreamingQuery query = df.select(col("__eventTime").as("event_time"))
                .withWatermark("event_time","1 minute")
                .groupBy(window(col("event_time"),"1 minute","1 minute"))
                //.groupBy("event_time")
                .count().withColumn("process_time",current_timestamp())
                .writeStream()
                .outputMode("append")
                .format("console")
                //.trigger(Trigger.ProcessingTime("1 minute"))
                **.option("checkpointLocation","G:/output/checkpoint")**
                .start();
        query.awaitTermination();

java.lang.NoClassDefFoundError: org/apache/pulsar/shade/org/apache/commons/io/IOUtils
	at org.apache.spark.sql.pulsar.PulsarSourceInitialOffsetWriter.deserialize(PulsarSources.scala:140)
	at org.apache.spark.sql.pulsar.PulsarSourceInitialOffsetWriter.deserialize(PulsarSources.scala:127)
	at org.apache.spark.sql.execution.streaming.HDFSMetadataLog.get(HDFSMetadataLog.scala:145)
	at org.apache.spark.sql.pulsar.PulsarSourceInitialOffsetWriter.getInitialOffset(PulsarSources.scala:164)

**Comment by daileizhi** [comment]
Do the follow steps and repackage，the problem can be resolved.

1、Get  the source，add dependency to the pom.xml
**<dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.4</version>
    </dependency>**

2、 Add commons-io to the artifactSet
<phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <promoteTransitiveDependencies>true</promoteTransitiveDependencies>
              <minimizeJar>false</minimizeJar>

              <artifactSet>
                <includes>
                  <include>com.github.luben:*</include>
                  <include>javax.*:*</include>
                  <include>org.apache.pulsar*:*</include>
                  <include>org.bouncycastle*:*</include>
                  <include>org.lz4*:*</include>
		  <include>commons-io:commons-io:jar:*</include>
                </includes>
              </artifactSet>
3、mvn package -DskipTests

**Comment by yjshen** [comment]
Hi @daileizhi, could you please create a pull request for this issue, since you already resolve it? Thanks very much for your job!
