### ISSUE TITLE
[FEATURE] Support reading with a different versioned schema

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-spark#25]
*Motivation*

Pulsar support schema evolution. Each pulsar message is associated with a schema version. Pulsar Spark Integration should be able to handle schema properly.

Related Issue: #2

**Comment by syhily** [comment]
I think this should be divide into two kind of requirements.

1. Support schema evolution by sending the schema to Pulsar on Producer.
2. Support reading different types of messages by its schema version.
