### ISSUE TITLE
[BUG] Failed to create subscription because of HTTP 307 Redirect.

### ISSUE THREAD

**Issue by yjshen** [streamnative/pulsar-spark#28]
![4011579595142_ pic_hd](https://user-images.githubusercontent.com/1387718/72792975-cfe53780-3c74-11ea-8e3f-81a9efe26999.jpg)

**Comment by yjshen** [comment]
Tracked here in Pulsar repo: https://github.com/streamnative/pulsar/issues/603

**Comment by yjshen** [comment]
This issue is caused by two subsequent issues:
- firstly, many of the REST APIs respond with 307 temporary redirects but not annotate them explicitly. (https://github.com/apache/pulsar/pull/6227)
- PulsarAdmin should deal with 307 but didn't.

**Comment by syhily** [comment]
The 307 redirect issue should be fixed now. https://github.com/apache/pulsar/issues/15546
