### ISSUE TITLE
[FEATURE] StartingOffsets doesn't work with BatchMessageId

### ISSUE THREAD

**Issue by kevin-kosmos** [streamnative/pulsar-spark#34]
Hi,

I'm trying to use startingOffsets on my topic, but messages id of my topic are instance of BatchMessageIdImpl (with batchIndex set). 
I have tried with a topic where messages id are basic messages id (MessageIdImpl) and everything works well. 
For example: I have 10 messages (sent with batching producer) in my topic. I set startingOffsets with this messageId : 39637:0:- 1:**4**
But Spark should shows next 6 messages but it shows nothing. 

There is my producer code : 
`       

        public class Producer {

	public static void main(String[] args) throws Exception {

		try (PulsarClient client = PulsarClient.builder()
				.serviceUrl("pulsar://localhost:6650")
				.build()) {

			Producer<String> producer = client
					.newProducer(Schema.STRING)
					.topic("topic")
                                        // if enableBatching is set to false, startingOffsets in application spark works well
					.enableBatching(true)
					.batchingMaxMessages(10)
					.blockIfQueueFull(false)
					.batchingMaxPublishDelay(100, TimeUnit.SECONDS)
					.create();

			CompletableFuture<MessageId> messageIdCompletableFuture = null;
			for (int i = 0; i < 10; i++) {
				messageIdCompletableFuture = producer.newMessage()
						.value(String.valueOf(i))
						.sendAsync();
			}

			messageIdCompletableFuture.get();
		}
	}
        }`

And my SparkApplication :
`

        public class SparkFunctionBatch {

	private static final String TOPIC = "persistent://public/default/topic2";

	public static void main(String[] args) {
		SparkSession spark = SparkSession.builder().appName("AppName").master("local[2]").getOrCreate();
		spark.sparkContext().setLogLevel("WARN");

		spark.udf().register("convert", (UDF1<byte[], String>)
				(messageIdBytes) -> MessageId.fromByteArray(messageIdBytes).toString(), DataTypes.StringType);

		Dataset<Row> kdecoleAppLog = spark
				.read()
				.format("pulsar")
				.option("service.url", "pulsar://localhost:6650")
				.option("admin.url", "http://localhost:8080")
				.option("topic", TOPIC)
				.option("startingOffsets", getStartingOffsets())
				.load();

		kdecoleAppLog
				.withColumn("__messageIdToString", callUDF("convert", col("__messageId")))
				.show(99999, false);
	}

	private static String getStartingOffsets() {
		String startingOffsets = "earliest";

		boolean calculatingStartingOffset = false;
		if (calculatingStartingOffset) {
			MessageId messageId = new BatchMessageIdImpl(39637, 0, -1, 4);

			Map<String, MessageId> jmap = new HashMap<>();
			jmap.put(TOPIC, messageId);

			scala.collection.immutable.Map<String, MessageId> map = JavaConverters.mapAsScalaMapConverter(jmap).asScala().toMap(
					Predef.conforms()
			);

			startingOffsets = JsonUtils.topicOffsets(map);
		}
		return startingOffsets;
	}
        }`

**Comment by nlu90** [comment]
close due to inactivity.
