### ISSUE TITLE
[FEATURE] Using custom subscription name

### ISSUE THREAD

**Issue by crazylab** [streamnative/pulsar-spark#35]
**Is your feature request related to a problem? Please describe.**
When the Spark Job starts, currently it uses random subscription names for consuming data. This makes it harder to log and debug.

**Describe the solution you'd like**
The subscription name can be taken as an `option` to the spark reader format. If the subscription name is not provided, we can continue generating random subscription name.

**Comment by syhily** [comment]
Custom  subscription name won't be supported for the limitation of Pulsar's reader API.
