### ISSUE TITLE
[FEATURE] Make this library available to maven central repository

### ISSUE THREAD

**Issue by crazylab** [streamnative/pulsar-spark#36]
**Is your feature request related to a problem? Please describe.**
Maven Central is the go to place to resolve any java dependency. Relying on the StreamNative hosted repository doesn't provide as much confidence. 

**Describe the solution you'd like**
Make this library available to maven central repository for better reliability.

**Additional context**
Sometime org policies/firewall doesn't allow to resolve dependencies from 3rd party sources. This feature will help adoption of the library.

**Comment by nburkecogito** [comment]
[It should be noted that bintray is being sunset on May 1st, 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). April 12 and April 26 will have brown outs on services. 

So yes, no one can download this jar file at the moment (it being April 12 in the brown out times).

May we request this as a higher priority?

**Comment by sijie** [comment]
@nburkecogito we are migrating to maven central. @codelipenghui can provide more updates here.

**Comment by luis-munoz** [comment]
Hi, Do you guys have an update or a workaround for this?
Currently bintray is giving a Forbidden error: https://dl.bintray.com/streamnative/maven

**Comment by nburkecogito** [comment]
I believe they [migrated it to maven already](https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-spark).

**Comment by syhily** [comment]
Closed for out of date.
