### ISSUE TITLE
[BUG] Incorrect string deserialization in pulsar-spark_2.11-2.4.5

### ISSUE THREAD

**Issue by szimon** [streamnative/pulsar-spark#40]
### Description

Pulsar message read into a structured stream is incorrectly deserialized if a `string` field has length over 127

### Environment

`scala 2.11`

`spark 2.4.7`

`pulsar-spark_2.11 2.4.5`

### Protobuf message definition

```protobuf
message Test {
  required string query = 1;
}
```

### Spark receiver
```scala
import org.apache.spark.SparkConf
import org.apache.spark.sql.SparkSession

object TestError {
  def main(args: Array[String]): Unit = {
    val conf = new SparkConf().setMaster("local[3]").setAppName("spark-stream-dev")
    conf.set("spark.sql.streaming.checkpointLocation", "./checkpoints")
    val spark = SparkSession.builder.config(conf).getOrCreate()
    import spark.implicits._

    val in = spark.readStream
      .format("pulsar")
      .option("service.url", "pulsar://pulsarHost:6650")
      .option("admin.url", "http://pulsarHost:8080")
      .option("topics", "persistent://sample/standalone/ns1/b")
      .load()

    val valueAsBytes = in.map { row =>
      val str = row.getAs[String]("value")
      val prettyBytes = str.getBytes().map(b => "%02X".format(b)) // pretty-print hex values
      prettyBytes.mkString(" ")
    }

    val out = valueAsBytes.writeStream
      .outputMode("append")
      .format("console")
      .start()

    val outCsv = valueAsBytes.writeStream
      .outputMode("append")
      .format("csv")
      .start("raw")


    out.awaitTermination()
    outCsv.awaitTermination()
  }
}
```

`query` field contains a string of length 127 (works correctly) or 128 (works incorrectly) letters.

 ### Correct behaviour - message of length 127 

Sent to pulsar:  
`0A 7F 61 61 ... 127 occurrences of letter 'a' ... 61 61`

Received using `bin/pulsar-client consume -n 0 --hex -s s1 persistent://sample/standalone/ns1/b`:  
`0A 7F 61 61 ... 127 occurrences of letter 'a' ... 61 61`

Received using spark-streaming (code above):  
`0A 7F 61 61 ... 127 occurrences of letter 'a' ... 61 61`

### Incorrect behaviour - message of length 128:

Sent to pulsar:  
`0A 80 01 61 61 ... 128 occurrences of letter 'a' ... 61 61`

Received using `bin/pulsar-client consume -n 0 --hex -s s1 persistent://sample/standalone/ns1/b`:  
`0A 80 01 61 61 ... 128 occurrences of letter 'a' ... 61 61`

Received using spark-streaming:  
`0A EF BF BD 01 61 61 ... 128 occurrences of letter 'a' ... 61 61`

Why is the `80 01` sequence read as `EF BF BF 01`?

**Comment by syhily** [comment]
I think this isn't a bug internally. This is because pulsar-spark doesn't support Protobuf and you just consume the protobuf encoded messages as Pure string.
