### ISSUE TITLE
[FEATURE] upgrade Spark DataSource V2 APIs for unify streaming and batch

### ISSUE THREAD

**Issue by jiazhai** [streamnative/pulsar-spark#43]
Thanks to @hanguyen6's proposal.  in PR #42 

Spark DataSource V2 APIs has been refactored to unify between streaming and batch. Should we upgrade our code to follow the updated abstraction:

https://issues.apache.org/jira/browse/SPARK-25390

write API refactor:
https://docs.google.com/document/d/1vI26UEuDpVuOjWw4WPoH2T6y8WAekwtI7qoowhOFnI4/edit#

read API refactoring:
https://docs.google.com/document/d/1uUmKCpWLdh9vHxP7AWJ9EgbwB_U6T3EJYNjhISGmiQg/edit#

I have updated code to follow that abstraction and can help if needed.

**Comment by jiazhai** [comment]
@hanguyen6 would you like to work on this issue?

**Comment by hanguyen6** [comment]
@jiazhai Yes, I am working on it right now. Will update when it completes

**Comment by hanguyen6** [comment]
@jiazhai Could you pls review PR #50 ?
