### ISSUE TITLE
[BUG] unnecessary subscription created when processing batches  

### ISSUE THREAD

**Issue by hanguyen6** [streamnative/pulsar-spark#44]
**Describe the bug**

Why do we need to create subscription when reader API is used and Spark manages offsets on its own. 
I can see new subscriptions got created and deleted by PulsarMetadataReader before and after committing a batch but dont see it useful. Is that legacy code and should be removed ? 

**Expected behavior**
- No subscription creation  needed when reader API is used 

**Additional context**
Spark version 2.4.5 and Pulsar version 2.5.0

**Comment by syhily** [comment]
This subscription is non-durable. So I don't think this is a bug. It's the internal behavior from Pulsar's Reader API.
