### ISSUE TITLE
[BUG] 500 Internal Server Error (Failed to get schema information) when trying to connect to the pulsar cluster

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/pulsar-spark#46]
**Describe the bug**

It seems that there is no schema defined with this topic. Is it expected that you are processing a topic without a schema. We might need to double-check if this connector supports reading a topic without a schema.

**Comment by codelipenghui** [comment]
ping @syhily Could you please help check this issue?

**Comment by syhily** [comment]
I have confirmed this issue, spark connector support reading message without a schema. This situation would fallback to `BytesSchema`

**Comment by codelipenghui** [comment]
@syhily The spark connector version is 2.4.5, could you please check if this version can fallback to BytesSchema?

**Comment by syhily** [comment]
This issue should be closed.
