### ISSUE TITLE
[BUG] Mismatch type - logicaltype 

### ISSUE THREAD

**Issue by mnit016** [streamnative/pulsar-spark#68]
**Describe the bug**
Field with int type - date logicalType is not working.

[JSONParser.scala](https://github.com/streamnative/pulsar-spark/blob/master/src/main/scala/org/apache/spark/sql/pulsar/JSONParser.scala#L177) map Date with Long & using timestamp format to parse date.
While [SchemaUtils.scala](https://github.com/streamnative/pulsar-spark/blob/master/src/main/scala/org/apache/spark/sql/pulsar/SchemaUtils.scala#L201) map Date with INT.

**Screenshots**
![image](https://user-images.githubusercontent.com/37934995/140733122-c9c562f7-706c-4ec6-acc7-6db5764fe1ae.png)
![image](https://user-images.githubusercontent.com/37934995/140733322-ec59781d-319f-41d6-9665-43dc53d07506.png)

**Comment by syhily** [comment]
@mnit016 Why you think this is a bug? Avro has a date "logicalType", which annotates int. For example:

`{"name": "date", "type": "int", "logicalType": "date"}`

**Comment by syhily** [comment]
Close for this is not a bug. Feel free to comment here.
