### ISSUE TITLE
[FEATURE] support pyspark

### ISSUE THREAD

**Issue by caibirdme** [streamnative/pulsar-spark#74]
**Is your feature request related to a problem? Please describe.**
It seems that for now only java version is supported for spark. I'm using pyspark, and when I try 2 use standard pulsar client to send data to pulsar, it returns error saying `PicklingError: Could not serialize object: RuntimeError: Pickling of "pulsar.Producer" instances is not enabled`

**Describe the solution you'd like**
also support pyspark

**Comment by nlu90** [comment]
#139
