### ISSUE TITLE
[FEATURE] Can I have one topic for each subscription name

### ISSUE THREAD

**Issue by xiongmozhou** [streamnative/pulsar-spark#85]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syhily** [comment]
Hi @xiongmozhou, Can you clarify your feature request? I can't understand what you mean.

**Comment by syhily** [comment]
The pulsar-spark is using Pulsar's reader API which hides the subscription name internally. No need to care about the subscription.
