### ISSUE TITLE
[BUG] Using the connector produces a scala.reflect.internal.Symbols$CyclicReference exception

### ISSUE THREAD

**Issue by honderdzevenduuzend** [streamnative/pulsar-spark#92]
Using the connector crashes Spark during initialization of the connector. See issue #91.

This exception does not occur when Pulsar version 2.4.2 is used to build the connector.

PR #93 provides a test that reproduces this behaviour.

**Comment by syhily** [comment]
I don't think this related to Pulsar's version.
